Create Adb
jarhot1992/Remote-ADB pull request #40
Opened 2023-05-11 05:52 UTC by Savag353aba55

2023-05-21 07:31 UTC, Himniharvest approved these changes

2023-05-21 07:31 UTC, Himniharvest commented on Adb
> +
```suggestion
[
```

2023-05-24 09:00 UTC, charlykt commented
https://patch-diff.githubusercontent.com/raw/jarhot1992/Remote-ADB/pull/40.diff

2023-06-08 09:57 UTC, TA20231980 requested changes
- [ ] - @Savag353aba55

2023-06-11 08:12 UTC, Priyadiwidjaja929269 commented on Adb
> +
❤️‍🩹❤️‍🩹

2023-06-11 08:12 UTC, Priyadiwidjaja929269 commented on Adb
> +
❤️‍🩹❤️‍🩹

2023-07-13 03:40 UTC, closed without merging